# Generated by Django 4.1.2 on 2022-11-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating_number',
            field=models.IntegerField(null=True),
        ),
    ]
