# Generated by Django 4.1.2 on 2022-11-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movie_rating_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating_number',
        ),
    ]
